import { createContext, useContext, useState, useCallback, ReactNode } from "react";

export type Language = 'en' | 'es' | 'fr' | 'de' | 'pt' | 'it' | 'ja' | 'ko' | 'zh' | 'ar' | 'ru' | 'tr' | 'hi' | 'nl' | 'pl' | 'sv' | 'th' | 'vi' | 'id';

interface LanguageInfo {
  code: Language;
  name: string;
  nativeName: string;
  flag: string;
}

export const LANGUAGES: LanguageInfo[] = [
  { code: 'en', name: 'English', nativeName: 'English', flag: '🇬🇧' },
  { code: 'es', name: 'Spanish', nativeName: 'Español', flag: '🇪🇸' },
  { code: 'fr', name: 'French', nativeName: 'Français', flag: '🇫🇷' },
  { code: 'de', name: 'German', nativeName: 'Deutsch', flag: '🇩🇪' },
  { code: 'pt', name: 'Portuguese', nativeName: 'Português', flag: '🇧🇷' },
  { code: 'it', name: 'Italian', nativeName: 'Italiano', flag: '🇮🇹' },
  { code: 'ja', name: 'Japanese', nativeName: '日本語', flag: '🇯🇵' },
  { code: 'ko', name: 'Korean', nativeName: '한국어', flag: '🇰🇷' },
  { code: 'zh', name: 'Chinese', nativeName: '中文', flag: '🇨🇳' },
  { code: 'ar', name: 'Arabic', nativeName: 'العربية', flag: '🇸🇦' },
  { code: 'ru', name: 'Russian', nativeName: 'Русский', flag: '🇷🇺' },
  { code: 'tr', name: 'Turkish', nativeName: 'Türkçe', flag: '🇹🇷' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', flag: '🇮🇳' },
  { code: 'nl', name: 'Dutch', nativeName: 'Nederlands', flag: '🇳🇱' },
  { code: 'pl', name: 'Polish', nativeName: 'Polski', flag: '🇵🇱' },
  { code: 'sv', name: 'Swedish', nativeName: 'Svenska', flag: '🇸🇪' },
  { code: 'th', name: 'Thai', nativeName: 'ไทย', flag: '🇹🇭' },
  { code: 'vi', name: 'Vietnamese', nativeName: 'Tiếng Việt', flag: '🇻🇳' },
  { code: 'id', name: 'Indonesian', nativeName: 'Bahasa Indonesia', flag: '🇮🇩' },
];

type TranslationKey = 
  | 'bets' | 'predict' | 'aiBetting' | 'myBets' | 'revenue' | 'dashboard'
  | 'promotions' | 'trade' | 'streaming' | 'leaderboard' | 'activity' | 'parlays'
  | 'withdraw' | 'whitepaper' | 'searchTeams' | 'favorites' | 'withOdds'
  | 'live' | 'upcoming' | 'loading' | 'noEvents' | 'bettingClosed'
  | 'betSlip' | 'parlay' | 'tapOdds' | 'stake' | 'potentialWin' | 'placeBet'
  | 'connectWallet' | 'disconnect' | 'balance' | 'deposit' | 'totalBets'
  | 'activeBets' | 'volume' | 'matches' | 'match' | 'home' | 'draw' | 'away'
  | 'over' | 'under' | 'cashOut' | 'cashOutConfirm' | 'notifications'
  | 'noNotifications' | 'betWon' | 'betLost' | 'betSettled' | 'clearAll'
  | 'verifiedOnSui' | 'poweredBy' | 'language' | 'starTeams' | 'formulaNote'
  | 'mmaNote' | 'clear' | 'viewAll'
  | 'heroTitle' | 'heroSui' | 'heroSubtitle' | 'liveMarkets' | 'sports'
  | 'settlement' | 'onChain' | 'betsSettled' | 'sbetsVolume' | 'viewContract'
  | 'more' | 'buyNow' | 'checkBackLater' | 'noEventsTab';

const translations: Record<Language, Record<TranslationKey, string>> = {
  en: {
    bets: 'Bets', predict: 'Predict', aiBetting: 'AI Betting', myBets: 'My Bets',
    revenue: 'Revenue', dashboard: 'Dashboard', promotions: 'Promotions', trade: 'Trade',
    streaming: 'Streaming', leaderboard: 'Leaderboard', activity: 'Activity', parlays: 'Parlays',
    withdraw: 'Withdraw', whitepaper: 'Whitepaper', searchTeams: 'Search teams, leagues...',
    favorites: 'Favorites', withOdds: 'With Odds', live: 'Live', upcoming: 'Upcoming',
    loading: 'Loading events...', noEvents: 'No events available',
    bettingClosed: 'Betting closed', betSlip: 'Bet Slip', parlay: 'Parlay',
    tapOdds: 'Tap on odds to add selections', stake: 'Stake', potentialWin: 'Potential Win',
    placeBet: 'Place Bet', connectWallet: 'Connect Wallet', disconnect: 'Disconnect',
    balance: 'Balance', deposit: 'Deposit', totalBets: 'Total Bets', activeBets: 'Active Bets',
    volume: 'Volume', matches: 'matches', match: 'match', home: 'Home', draw: 'Draw', away: 'Away',
    over: 'Over', under: 'Under', cashOut: 'Cash Out', cashOutConfirm: 'Confirm Cash Out',
    notifications: 'Notifications', noNotifications: 'No new notifications',
    betWon: 'Bet Won!', betLost: 'Bet Lost', betSettled: 'Bet Settled',
    clearAll: 'Clear All', verifiedOnSui: 'Verified on Sui', poweredBy: 'Powered by',
    language: 'Language', starTeams: 'Star some teams to see them here!',
    formulaNote: 'Formula 1 races update weekly', mmaNote: 'MMA events update periodically',
    clear: 'Clear', viewAll: 'View All',
    heroTitle: 'Decentralized Sports Betting on', heroSui: 'Sui',
    heroSubtitle: 'Bet with SBETS or SUI \u00b7 Transparent odds \u00b7 Instant on-chain settlement',
    liveMarkets: 'Live Markets', sports: 'Sports', settlement: 'Settlement', onChain: 'On-Chain',
    betsSettled: 'Bets Settled', sbetsVolume: 'SBETS Volume', viewContract: 'View Contract',
    more: 'More', buyNow: 'Buy Now', checkBackLater: 'Check back later for more events',
    noEventsTab: 'No {tab} events available',
  },
  es: {
    bets: 'Apuestas', predict: 'Predecir', aiBetting: 'IA Apuestas', myBets: 'Mis Apuestas',
    revenue: 'Ingresos', dashboard: 'Panel', promotions: 'Promociones', trade: 'Comercio',
    streaming: 'Streaming', leaderboard: 'Clasificación', activity: 'Actividad', parlays: 'Combinadas',
    withdraw: 'Retirar', whitepaper: 'Whitepaper', searchTeams: 'Buscar equipos, ligas...',
    favorites: 'Favoritos', withOdds: 'Con Cuotas', live: 'En Vivo', upcoming: 'Próximos',
    loading: 'Cargando eventos...', noEvents: 'No hay eventos disponibles',
    bettingClosed: 'Apuestas cerradas', betSlip: 'Boleto', parlay: 'Combinada',
    tapOdds: 'Toca las cuotas para añadir selecciones', stake: 'Apuesta', potentialWin: 'Ganancia Potencial',
    placeBet: 'Apostar', connectWallet: 'Conectar Billetera', disconnect: 'Desconectar',
    balance: 'Saldo', deposit: 'Depositar', totalBets: 'Total Apuestas', activeBets: 'Apuestas Activas',
    volume: 'Volumen', matches: 'partidos', match: 'partido', home: 'Local', draw: 'Empate', away: 'Visitante',
    over: 'Más de', under: 'Menos de', cashOut: 'Cobrar', cashOutConfirm: 'Confirmar Cobro',
    notifications: 'Notificaciones', noNotifications: 'Sin notificaciones nuevas',
    betWon: '¡Apuesta Ganada!', betLost: 'Apuesta Perdida', betSettled: 'Apuesta Resuelta',
    clearAll: 'Borrar Todo', verifiedOnSui: 'Verificado en Sui', poweredBy: 'Impulsado por',
    language: 'Idioma', starTeams: '¡Marca equipos como favoritos para verlos aquí!',
    formulaNote: 'Las carreras de F1 se actualizan semanalmente', mmaNote: 'Los eventos de MMA se actualizan periódicamente',
    clear: 'Borrar', viewAll: 'Ver Todo',
    heroTitle: 'Apuestas Deportivas Descentralizadas en', heroSui: 'Sui',
    heroSubtitle: 'Apuesta con SBETS o SUI \u00b7 Cuotas transparentes \u00b7 Liquidación instantánea on-chain',
    liveMarkets: 'Mercados en Vivo', sports: 'Deportes', settlement: 'Liquidación', onChain: 'On-Chain',
    betsSettled: 'Apuestas Liquidadas', sbetsVolume: 'Volumen SBETS', viewContract: 'Ver Contrato',
    more: 'Más', buyNow: 'Comprar', checkBackLater: 'Vuelve más tarde para más eventos',
    noEventsTab: 'No hay eventos {tab} disponibles',
  },
  fr: {
    bets: 'Paris', predict: 'Prédire', aiBetting: 'Paris IA', myBets: 'Mes Paris',
    revenue: 'Revenus', dashboard: 'Tableau de bord', promotions: 'Promotions', trade: 'Échange',
    streaming: 'Streaming', leaderboard: 'Classement', activity: 'Activité', parlays: 'Combinés',
    withdraw: 'Retirer', whitepaper: 'Whitepaper', searchTeams: 'Rechercher équipes, ligues...',
    favorites: 'Favoris', withOdds: 'Avec Cotes', live: 'En Direct', upcoming: 'À Venir',
    loading: 'Chargement des événements...', noEvents: 'Aucun événement disponible',
    bettingClosed: 'Paris fermés', betSlip: 'Ticket', parlay: 'Combiné',
    tapOdds: 'Touchez les cotes pour ajouter des sélections', stake: 'Mise', potentialWin: 'Gain Potentiel',
    placeBet: 'Parier', connectWallet: 'Connecter Portefeuille', disconnect: 'Déconnecter',
    balance: 'Solde', deposit: 'Déposer', totalBets: 'Total Paris', activeBets: 'Paris Actifs',
    volume: 'Volume', matches: 'matchs', match: 'match', home: 'Domicile', draw: 'Nul', away: 'Extérieur',
    over: 'Plus de', under: 'Moins de', cashOut: 'Encaisser', cashOutConfirm: 'Confirmer Encaissement',
    notifications: 'Notifications', noNotifications: 'Pas de nouvelles notifications',
    betWon: 'Pari Gagné !', betLost: 'Pari Perdu', betSettled: 'Pari Réglé',
    clearAll: 'Tout Effacer', verifiedOnSui: 'Vérifié sur Sui', poweredBy: 'Propulsé par',
    language: 'Langue', starTeams: 'Ajoutez des équipes en favoris pour les voir ici !',
    formulaNote: 'Les courses de F1 sont mises à jour chaque semaine', mmaNote: 'Les événements MMA sont mis à jour périodiquement',
    clear: 'Effacer', viewAll: 'Voir Tout',
    heroTitle: 'Paris Sportifs Décentralisés sur', heroSui: 'Sui',
      heroSubtitle: 'Pariez avec SBETS ou SUI \u00b7 Cotes transparentes \u00b7 Règlement instantané on-chain',
      liveMarkets: 'Marchés en Direct', sports: 'Sports', settlement: 'Règlement', onChain: 'On-Chain',
      betsSettled: 'Paris Réglés', sbetsVolume: 'Volume SBETS', viewContract: 'Voir le Contrat',
      more: 'Plus', buyNow: 'Acheter', checkBackLater: 'Revenez plus tard pour plus d\'événements',
      noEventsTab: 'Aucun événement {tab} disponible',
  },
  de: {
    bets: 'Wetten', predict: 'Vorhersagen', aiBetting: 'KI-Wetten', myBets: 'Meine Wetten',
    revenue: 'Einnahmen', dashboard: 'Übersicht', promotions: 'Aktionen', trade: 'Handel',
    streaming: 'Streaming', leaderboard: 'Rangliste', activity: 'Aktivität', parlays: 'Kombiwetten',
    withdraw: 'Abheben', whitepaper: 'Whitepaper', searchTeams: 'Teams, Ligen suchen...',
    favorites: 'Favoriten', withOdds: 'Mit Quoten', live: 'Live', upcoming: 'Kommend',
    loading: 'Lade Ereignisse...', noEvents: 'Keine Ereignisse verfügbar',
    bettingClosed: 'Wetten geschlossen', betSlip: 'Wettschein', parlay: 'Kombiwette',
    tapOdds: 'Tippe auf Quoten um Auswahlen hinzuzufügen', stake: 'Einsatz', potentialWin: 'Möglicher Gewinn',
    placeBet: 'Wette platzieren', connectWallet: 'Wallet verbinden', disconnect: 'Trennen',
    balance: 'Guthaben', deposit: 'Einzahlen', totalBets: 'Gesamte Wetten', activeBets: 'Aktive Wetten',
    volume: 'Volumen', matches: 'Spiele', match: 'Spiel', home: 'Heim', draw: 'Unentschieden', away: 'Auswärts',
    over: 'Über', under: 'Unter', cashOut: 'Auszahlen', cashOutConfirm: 'Auszahlung bestätigen',
    notifications: 'Benachrichtigungen', noNotifications: 'Keine neuen Benachrichtigungen',
    betWon: 'Wette gewonnen!', betLost: 'Wette verloren', betSettled: 'Wette abgerechnet',
    clearAll: 'Alles löschen', verifiedOnSui: 'Verifiziert auf Sui', poweredBy: 'Betrieben von',
    language: 'Sprache', starTeams: 'Markiere Teams als Favoriten!',
    formulaNote: 'F1-Rennen werden wöchentlich aktualisiert', mmaNote: 'MMA-Events werden periodisch aktualisiert',
    clear: 'Löschen', viewAll: 'Alle ansehen',
    heroTitle: 'Dezentrales Sportwetten auf', heroSui: 'Sui',
      heroSubtitle: 'Wette mit SBETS oder SUI \u00b7 Transparente Quoten \u00b7 Sofortige On-Chain-Abrechnung',
      liveMarkets: 'Live-Märkte', sports: 'Sportarten', settlement: 'Abrechnung', onChain: 'On-Chain',
      betsSettled: 'Wetten abgerechnet', sbetsVolume: 'SBETS Volumen', viewContract: 'Vertrag ansehen',
      more: 'Mehr', buyNow: 'Kaufen', checkBackLater: 'Schauen Sie später nach weiteren Events',
      noEventsTab: 'Keine {tab} Events verfügbar',
  },
  pt: {
    bets: 'Apostas', predict: 'Prever', aiBetting: 'Apostas IA', myBets: 'Minhas Apostas',
    revenue: 'Receita', dashboard: 'Painel', promotions: 'Promoções', trade: 'Negociar',
    streaming: 'Streaming', leaderboard: 'Ranking', activity: 'Atividade', parlays: 'Múltiplas',
    withdraw: 'Sacar', whitepaper: 'Whitepaper', searchTeams: 'Buscar times, ligas...',
    favorites: 'Favoritos', withOdds: 'Com Odds', live: 'Ao Vivo', upcoming: 'Próximos',
    loading: 'Carregando eventos...', noEvents: 'Nenhum evento disponível',
    bettingClosed: 'Apostas encerradas', betSlip: 'Bilhete', parlay: 'Múltipla',
    tapOdds: 'Toque nas odds para adicionar seleções', stake: 'Valor', potentialWin: 'Ganho Potencial',
    placeBet: 'Apostar', connectWallet: 'Conectar Carteira', disconnect: 'Desconectar',
    balance: 'Saldo', deposit: 'Depositar', totalBets: 'Total de Apostas', activeBets: 'Apostas Ativas',
    volume: 'Volume', matches: 'jogos', match: 'jogo', home: 'Casa', draw: 'Empate', away: 'Fora',
    over: 'Mais de', under: 'Menos de', cashOut: 'Sacar', cashOutConfirm: 'Confirmar Saque',
    notifications: 'Notificações', noNotifications: 'Sem novas notificações',
    betWon: 'Aposta Ganha!', betLost: 'Aposta Perdida', betSettled: 'Aposta Resolvida',
    clearAll: 'Limpar Tudo', verifiedOnSui: 'Verificado no Sui', poweredBy: 'Desenvolvido por',
    language: 'Idioma', starTeams: 'Marque times como favoritos para vê-los aqui!',
    formulaNote: 'Corridas de F1 são atualizadas semanalmente', mmaNote: 'Eventos de MMA são atualizados periodicamente',
    clear: 'Limpar', viewAll: 'Ver Tudo',
    heroTitle: 'Apostas Esportivas Descentralizadas em', heroSui: 'Sui',
      heroSubtitle: 'Aposte com SBETS ou SUI \u00b7 Odds transparentes \u00b7 Liquidação instantânea on-chain',
      liveMarkets: 'Mercados ao Vivo', sports: 'Esportes', settlement: 'Liquidação', onChain: 'On-Chain',
      betsSettled: 'Apostas Liquidadas', sbetsVolume: 'Volume SBETS', viewContract: 'Ver Contrato',
      more: 'Mais', buyNow: 'Comprar', checkBackLater: 'Volte mais tarde para mais eventos',
      noEventsTab: 'Nenhum evento {tab} disponível',
  },
  it: {
    bets: 'Scommesse', predict: 'Prevedere', aiBetting: 'IA Scommesse', myBets: 'Le Mie Scommesse',
    revenue: 'Entrate', dashboard: 'Pannello', promotions: 'Promozioni', trade: 'Scambio',
    streaming: 'Streaming', leaderboard: 'Classifica', activity: 'Attività', parlays: 'Multiple',
    withdraw: 'Prelevare', whitepaper: 'Whitepaper', searchTeams: 'Cerca squadre, campionati...',
    favorites: 'Preferiti', withOdds: 'Con Quote', live: 'In Diretta', upcoming: 'Prossimi',
    loading: 'Caricamento eventi...', noEvents: 'Nessun evento disponibile',
    bettingClosed: 'Scommesse chiuse', betSlip: 'Schedina', parlay: 'Multipla',
    tapOdds: 'Tocca le quote per aggiungere selezioni', stake: 'Puntata', potentialWin: 'Vincita Potenziale',
    placeBet: 'Scommetti', connectWallet: 'Connetti Portafoglio', disconnect: 'Disconnetti',
    balance: 'Saldo', deposit: 'Deposita', totalBets: 'Totale Scommesse', activeBets: 'Scommesse Attive',
    volume: 'Volume', matches: 'partite', match: 'partita', home: 'Casa', draw: 'Pareggio', away: 'Trasferta',
    over: 'Più di', under: 'Meno di', cashOut: 'Incassa', cashOutConfirm: 'Conferma Incasso',
    notifications: 'Notifiche', noNotifications: 'Nessuna nuova notifica',
    betWon: 'Scommessa Vinta!', betLost: 'Scommessa Persa', betSettled: 'Scommessa Regolata',
    clearAll: 'Cancella Tutto', verifiedOnSui: 'Verificato su Sui', poweredBy: 'Alimentato da',
    language: 'Lingua', starTeams: 'Aggiungi squadre ai preferiti per vederle qui!',
    formulaNote: 'Le gare di F1 vengono aggiornate settimanalmente', mmaNote: 'Gli eventi MMA vengono aggiornati periodicamente',
    clear: 'Cancella', viewAll: 'Vedi Tutto',
    heroTitle: 'Scommesse Sportive Decentralizzate su', heroSui: 'Sui',
      heroSubtitle: 'Scommetti con SBETS o SUI \u00b7 Quote trasparenti \u00b7 Regolamento istantaneo on-chain',
      liveMarkets: 'Mercati Live', sports: 'Sport', settlement: 'Regolamento', onChain: 'On-Chain',
      betsSettled: 'Scommesse Regolate', sbetsVolume: 'Volume SBETS', viewContract: 'Vedi Contratto',
      more: 'Altro', buyNow: 'Acquista', checkBackLater: 'Torna più tardi per altri eventi',
      noEventsTab: 'Nessun evento {tab} disponibile',
  },
  ja: {
    bets: 'ベット', predict: '予測', aiBetting: 'AIベッティング', myBets: 'マイベット',
    revenue: '収益', dashboard: 'ダッシュボード', promotions: 'プロモーション', trade: 'トレード',
    streaming: 'ストリーミング', leaderboard: 'ランキング', activity: 'アクティビティ', parlays: 'パーレイ',
    withdraw: '出金', whitepaper: 'ホワイトペーパー', searchTeams: 'チーム、リーグを検索...',
    favorites: 'お気に入り', withOdds: 'オッズあり', live: 'ライブ', upcoming: '今後',
    loading: 'イベント読み込み中...', noEvents: 'イベントがありません',
    bettingClosed: 'ベッティング終了', betSlip: 'ベットスリップ', parlay: 'パーレイ',
    tapOdds: 'オッズをタップして選択を追加', stake: '賭け金', potentialWin: '予想勝利金',
    placeBet: 'ベットする', connectWallet: 'ウォレット接続', disconnect: '切断',
    balance: '残高', deposit: '入金', totalBets: '合計ベット', activeBets: 'アクティブベット',
    volume: 'ボリューム', matches: '試合', match: '試合', home: 'ホーム', draw: '引き分け', away: 'アウェイ',
    over: 'オーバー', under: 'アンダー', cashOut: 'キャッシュアウト', cashOutConfirm: 'キャッシュアウト確認',
    notifications: '通知', noNotifications: '新しい通知はありません',
    betWon: 'ベット勝利！', betLost: 'ベット敗北', betSettled: 'ベット決済済み',
    clearAll: 'すべてクリア', verifiedOnSui: 'Sui上で検証済み', poweredBy: '提供元',
    language: '言語', starTeams: 'チームをお気に入りに追加してここに表示！',
    formulaNote: 'F1レースは毎週更新されます', mmaNote: 'MMAイベントは定期的に更新されます',
    clear: 'クリア', viewAll: 'すべて表示',
    heroTitle: '分散型スポーツベッティング', heroSui: 'Sui',
      heroSubtitle: 'SBETSまたはSUIで賭ける \u00b7 透明なオッズ \u00b7 即時オンチェーン決済',
      liveMarkets: 'ライブマーケット', sports: 'スポーツ', settlement: '決済', onChain: 'オンチェーン',
      betsSettled: '決済済みベット', sbetsVolume: 'SBETSボリューム', viewContract: 'コントラクトを見る',
      more: 'もっと見る', buyNow: '購入', checkBackLater: '後でもう一度確認してください',
      noEventsTab: '{tab}イベントがありません',
  },
  ko: {
    bets: '베팅', predict: '예측', aiBetting: 'AI 베팅', myBets: '내 베팅',
    revenue: '수익', dashboard: '대시보드', promotions: '프로모션', trade: '거래',
    streaming: '스트리밍', leaderboard: '리더보드', activity: '활동', parlays: '조합 베팅',
    withdraw: '출금', whitepaper: '백서', searchTeams: '팀, 리그 검색...',
    favorites: '즐겨찾기', withOdds: '배당 있는', live: '라이브', upcoming: '예정',
    loading: '이벤트 로딩 중...', noEvents: '이벤트가 없습니다',
    bettingClosed: '베팅 마감', betSlip: '베팅 슬립', parlay: '조합',
    tapOdds: '배당을 탭하여 선택 추가', stake: '베팅액', potentialWin: '예상 수익',
    placeBet: '베팅하기', connectWallet: '지갑 연결', disconnect: '연결 해제',
    balance: '잔액', deposit: '입금', totalBets: '총 베팅', activeBets: '진행 중 베팅',
    volume: '거래량', matches: '경기', match: '경기', home: '홈', draw: '무승부', away: '원정',
    over: '오버', under: '언더', cashOut: '캐시아웃', cashOutConfirm: '캐시아웃 확인',
    notifications: '알림', noNotifications: '새 알림이 없습니다',
    betWon: '베팅 승리!', betLost: '베팅 패배', betSettled: '베팅 정산',
    clearAll: '모두 삭제', verifiedOnSui: 'Sui 인증', poweredBy: '제공',
    language: '언어', starTeams: '팀을 즐겨찾기에 추가하세요!',
    formulaNote: 'F1 레이스는 매주 업데이트됩니다', mmaNote: 'MMA 이벤트는 주기적으로 업데이트됩니다',
    clear: '삭제', viewAll: '모두 보기',
    heroTitle: '탈중앙화 스포츠 베팅', heroSui: 'Sui',
      heroSubtitle: 'SBETS 또는 SUI로 베팅 \u00b7 투명한 배당 \u00b7 즉시 온체인 정산',
      liveMarkets: '라이브 마켓', sports: '스포츠', settlement: '정산', onChain: '온체인',
      betsSettled: '정산된 베팅', sbetsVolume: 'SBETS 거래량', viewContract: '컨트랙트 보기',
      more: '더보기', buyNow: '구매', checkBackLater: '나중에 다시 확인해주세요',
      noEventsTab: '{tab} 이벤트가 없습니다',
  },
  zh: {
    bets: '投注', predict: '预测', aiBetting: 'AI投注', myBets: '我的投注',
    revenue: '收入', dashboard: '仪表板', promotions: '促销', trade: '交易',
    streaming: '直播', leaderboard: '排行榜', activity: '动态', parlays: '串关',
    withdraw: '提款', whitepaper: '白皮书', searchTeams: '搜索球队、联赛...',
    favorites: '收藏', withOdds: '有赔率', live: '直播中', upcoming: '即将开始',
    loading: '加载赛事中...', noEvents: '暂无赛事',
    bettingClosed: '投注已关闭', betSlip: '投注单', parlay: '串关',
    tapOdds: '点击赔率添加选择', stake: '投注额', potentialWin: '潜在收益',
    placeBet: '下注', connectWallet: '连接钱包', disconnect: '断开连接',
    balance: '余额', deposit: '充值', totalBets: '总投注', activeBets: '进行中投注',
    volume: '交易量', matches: '场比赛', match: '场比赛', home: '主队', draw: '平局', away: '客队',
    over: '大于', under: '小于', cashOut: '兑现', cashOutConfirm: '确认兑现',
    notifications: '通知', noNotifications: '暂无新通知',
    betWon: '投注获胜！', betLost: '投注失败', betSettled: '投注已结算',
    clearAll: '清除全部', verifiedOnSui: 'Sui链上验证', poweredBy: '技术支持',
    language: '语言', starTeams: '收藏球队以在此查看！',
    formulaNote: 'F1赛事每周更新', mmaNote: 'MMA赛事定期更新',
    clear: '清除', viewAll: '查看全部',
    heroTitle: '去中心化体育博彩', heroSui: 'Sui',
      heroSubtitle: '使用SBETS或SUI投注 \u00b7 透明赔率 \u00b7 即时链上结算',
      liveMarkets: '实时市场', sports: '体育', settlement: '结算', onChain: '链上',
      betsSettled: '已结算投注', sbetsVolume: 'SBETS交易量', viewContract: '查看合约',
      more: '更多', buyNow: '购买', checkBackLater: '稍后再来查看更多赛事',
      noEventsTab: '暂无{tab}赛事',
  },
  ar: {
    bets: 'رهانات', predict: 'تنبؤ', aiBetting: 'رهانات الذكاء الاصطناعي', myBets: 'رهاناتي',
    revenue: 'الإيرادات', dashboard: 'لوحة القيادة', promotions: 'العروض', trade: 'تداول',
    streaming: 'البث', leaderboard: 'المتصدرون', activity: 'النشاط', parlays: 'المجمعة',
    withdraw: 'سحب', whitepaper: 'الورقة البيضاء', searchTeams: 'ابحث عن فرق، دوريات...',
    favorites: 'المفضلة', withOdds: 'مع احتمالات', live: 'مباشر', upcoming: 'قادم',
    loading: 'جاري تحميل الأحداث...', noEvents: 'لا توجد أحداث متاحة',
    bettingClosed: 'الرهانات مغلقة', betSlip: 'قسيمة الرهان', parlay: 'مجمعة',
    tapOdds: 'اضغط على الاحتمالات لإضافة اختيارات', stake: 'المبلغ', potentialWin: 'الربح المحتمل',
    placeBet: 'راهن', connectWallet: 'ربط المحفظة', disconnect: 'قطع الاتصال',
    balance: 'الرصيد', deposit: 'إيداع', totalBets: 'إجمالي الرهانات', activeBets: 'رهانات نشطة',
    volume: 'الحجم', matches: 'مباريات', match: 'مباراة', home: 'محلي', draw: 'تعادل', away: 'زائر',
    over: 'أكثر من', under: 'أقل من', cashOut: 'صرف', cashOutConfirm: 'تأكيد الصرف',
    notifications: 'إشعارات', noNotifications: 'لا توجد إشعارات جديدة',
    betWon: 'رهان فائز!', betLost: 'رهان خاسر', betSettled: 'تمت تسوية الرهان',
    clearAll: 'مسح الكل', verifiedOnSui: 'موثق على Sui', poweredBy: 'مدعوم من',
    language: 'اللغة', starTeams: 'أضف فرقاً للمفضلة لرؤيتها هنا!',
    formulaNote: 'يتم تحديث سباقات الفورمولا 1 أسبوعياً', mmaNote: 'يتم تحديث أحداث MMA بشكل دوري',
    clear: 'مسح', viewAll: 'عرض الكل',
    heroTitle: 'مراهنات رياضية لامركزية على', heroSui: 'Sui',
      heroSubtitle: 'راهن بـ SBETS أو SUI \u00b7 احتمالات شفافة \u00b7 تسوية فورية على السلسلة',
      liveMarkets: 'أسواق مباشرة', sports: 'رياضات', settlement: 'تسوية', onChain: 'على السلسلة',
      betsSettled: 'رهانات مسوّاة', sbetsVolume: 'حجم SBETS', viewContract: 'عرض العقد',
      more: 'المزيد', buyNow: 'اشتري', checkBackLater: 'عد لاحقاً لمزيد من الأحداث',
      noEventsTab: 'لا توجد أحداث {tab} متاحة',
  },
  ru: {
    bets: 'Ставки', predict: 'Прогноз', aiBetting: 'ИИ Ставки', myBets: 'Мои Ставки',
    revenue: 'Доход', dashboard: 'Панель', promotions: 'Акции', trade: 'Обмен',
    streaming: 'Стриминг', leaderboard: 'Рейтинг', activity: 'Активность', parlays: 'Экспрессы',
    withdraw: 'Вывод', whitepaper: 'Whitepaper', searchTeams: 'Поиск команд, лиг...',
    favorites: 'Избранное', withOdds: 'С коэффициентами', live: 'Лайв', upcoming: 'Предстоящие',
    loading: 'Загрузка событий...', noEvents: 'Нет доступных событий',
    bettingClosed: 'Ставки закрыты', betSlip: 'Купон', parlay: 'Экспресс',
    tapOdds: 'Нажмите на коэффициент для добавления', stake: 'Сумма', potentialWin: 'Возможный выигрыш',
    placeBet: 'Сделать ставку', connectWallet: 'Подключить кошелёк', disconnect: 'Отключить',
    balance: 'Баланс', deposit: 'Пополнить', totalBets: 'Всего ставок', activeBets: 'Активные ставки',
    volume: 'Объём', matches: 'матчей', match: 'матч', home: 'Дома', draw: 'Ничья', away: 'В гостях',
    over: 'Больше', under: 'Меньше', cashOut: 'Обналичить', cashOutConfirm: 'Подтвердить обналичивание',
    notifications: 'Уведомления', noNotifications: 'Нет новых уведомлений',
    betWon: 'Ставка выиграна!', betLost: 'Ставка проиграна', betSettled: 'Ставка рассчитана',
    clearAll: 'Очистить всё', verifiedOnSui: 'Проверено на Sui', poweredBy: 'Работает на',
    language: 'Язык', starTeams: 'Добавьте команды в избранное!',
    formulaNote: 'Гонки Ф1 обновляются еженедельно', mmaNote: 'MMA события обновляются периодически',
    clear: 'Очистить', viewAll: 'Смотреть все',
    heroTitle: 'Децентрализованные спортивные ставки на', heroSui: 'Sui',
      heroSubtitle: 'Ставьте с SBETS или SUI \u00b7 Прозрачные коэффициенты \u00b7 Мгновенный расчёт on-chain',
      liveMarkets: 'Живые рынки', sports: 'Виды спорта', settlement: 'Расчёт', onChain: 'On-Chain',
      betsSettled: 'Рассчитанные ставки', sbetsVolume: 'Объём SBETS', viewContract: 'Смотреть контракт',
      more: 'Ещё', buyNow: 'Купить', checkBackLater: 'Зайдите позже для новых событий',
      noEventsTab: 'Нет {tab} событий',
  },
  tr: {
    bets: 'Bahisler', predict: 'Tahmin', aiBetting: 'AI Bahis', myBets: 'Bahislerim',
    revenue: 'Gelir', dashboard: 'Panel', promotions: 'Promosyonlar', trade: 'Ticaret',
    streaming: 'Yayın', leaderboard: 'Sıralama', activity: 'Etkinlik', parlays: 'Kombine',
    withdraw: 'Çekim', whitepaper: 'Whitepaper', searchTeams: 'Takım, lig ara...',
    favorites: 'Favoriler', withOdds: 'Oranlı', live: 'Canlı', upcoming: 'Yaklaşan',
    loading: 'Etkinlikler yükleniyor...', noEvents: 'Etkinlik bulunmuyor',
    bettingClosed: 'Bahisler kapalı', betSlip: 'Kupon', parlay: 'Kombine',
    tapOdds: 'Seçim eklemek için oranlara dokunun', stake: 'Miktar', potentialWin: 'Olası Kazanç',
    placeBet: 'Bahis Yap', connectWallet: 'Cüzdan Bağla', disconnect: 'Bağlantıyı Kes',
    balance: 'Bakiye', deposit: 'Yatır', totalBets: 'Toplam Bahis', activeBets: 'Aktif Bahisler',
    volume: 'Hacim', matches: 'maç', match: 'maç', home: 'Ev Sahibi', draw: 'Berabere', away: 'Deplasman',
    over: 'Üst', under: 'Alt', cashOut: 'Nakde Çevir', cashOutConfirm: 'Nakde Çevirmeyi Onayla',
    notifications: 'Bildirimler', noNotifications: 'Yeni bildirim yok',
    betWon: 'Bahis Kazandı!', betLost: 'Bahis Kaybetti', betSettled: 'Bahis Sonuçlandı',
    clearAll: 'Tümünü Temizle', verifiedOnSui: "Sui'de Doğrulanmış", poweredBy: 'Destekleyen',
    language: 'Dil', starTeams: 'Takımları favorilere ekleyin!',
    formulaNote: 'F1 yarışları haftalık güncellenir', mmaNote: 'MMA etkinlikleri periyodik güncellenir',
    clear: 'Temizle', viewAll: 'Tümünü Gör',
    heroTitle: 'Merkezi Olmayan Spor Bahisleri', heroSui: 'Sui',
      heroSubtitle: 'SBETS veya SUI ile bahis yapın \u00b7 Şeffaf oranlar \u00b7 Anında on-chain uzlaşma',
      liveMarkets: 'Canlı Pazarlar', sports: 'Sporlar', settlement: 'Uzlaşma', onChain: 'On-Chain',
      betsSettled: 'Sonuçlanan Bahisler', sbetsVolume: 'SBETS Hacmi', viewContract: 'Sözleşmeyi Gör',
      more: 'Daha Fazla', buyNow: 'Satın Al', checkBackLater: 'Daha fazla etkinlik için sonra gelin',
      noEventsTab: '{tab} etkinlik bulunmuyor',
  },
  hi: {
    bets: 'शर्तें', predict: 'भविष्यवाणी', aiBetting: 'AI सट्टेबाजी', myBets: 'मेरी शर्तें',
    revenue: 'राजस्व', dashboard: 'डैशबोर्ड', promotions: 'प्रमोशन', trade: 'ट्रेड',
    streaming: 'स्ट्रीमिंग', leaderboard: 'लीडरबोर्ड', activity: 'गतिविधि', parlays: 'कॉम्बो बेट',
    withdraw: 'निकासी', whitepaper: 'व्हाइटपेपर', searchTeams: 'टीम, लीग खोजें...',
    favorites: 'पसंदीदा', withOdds: 'ऑड्स के साथ', live: 'लाइव', upcoming: 'आगामी',
    loading: 'इवेंट लोड हो रहे हैं...', noEvents: 'कोई इवेंट उपलब्ध नहीं',
    bettingClosed: 'सट्टेबाजी बंद', betSlip: 'बेट स्लिप', parlay: 'कॉम्बो',
    tapOdds: 'चयन जोड़ने के लिए ऑड्स पर टैप करें', stake: 'दांव', potentialWin: 'संभावित जीत',
    placeBet: 'शर्त लगाएं', connectWallet: 'वॉलेट जोड़ें', disconnect: 'डिस्कनेक्ट',
    balance: 'शेष', deposit: 'जमा', totalBets: 'कुल शर्तें', activeBets: 'सक्रिय शर्तें',
    volume: 'वॉल्यूम', matches: 'मैच', match: 'मैच', home: 'घरेलू', draw: 'ड्रॉ', away: 'बाहरी',
    over: 'ओवर', under: 'अंडर', cashOut: 'कैश आउट', cashOutConfirm: 'कैश आउट की पुष्टि करें',
    notifications: 'सूचनाएं', noNotifications: 'कोई नई सूचना नहीं',
    betWon: 'शर्त जीती!', betLost: 'शर्त हारी', betSettled: 'शर्त निपटान',
    clearAll: 'सब साफ करें', verifiedOnSui: 'Sui पर सत्यापित', poweredBy: 'द्वारा संचालित',
    language: 'भाषा', starTeams: 'यहां देखने के लिए टीमों को पसंदीदा में जोड़ें!',
    formulaNote: 'F1 रेस साप्ताहिक अपडेट होती हैं', mmaNote: 'MMA इवेंट समय-समय पर अपडेट होते हैं',
    clear: 'साफ करें', viewAll: 'सभी देखें',
    heroTitle: 'विकेंद्रीकृत खेल सट्टेबाजी', heroSui: 'Sui',
      heroSubtitle: 'SBETS या SUI से दांव लगाएं \u00b7 पारदर्शी ऑड्स \u00b7 तत्काल ऑन-चेन निपटान',
      liveMarkets: 'लाइव मार्केट', sports: 'खेल', settlement: 'निपटान', onChain: 'ऑन-चेन',
      betsSettled: 'निपटाए गए दांव', sbetsVolume: 'SBETS वॉल्यूम', viewContract: 'कॉन्ट्रैक्ट देखें',
      more: 'और', buyNow: 'खरीदें', checkBackLater: 'अधिक इवेंट के लिए बाद में आएं',
      noEventsTab: 'कोई {tab} इवेंट उपलब्ध नहीं',
  },
  nl: {
    bets: 'Weddenschappen', predict: 'Voorspellen', aiBetting: 'AI Wedden', myBets: 'Mijn Weddenschappen',
    revenue: 'Inkomsten', dashboard: 'Dashboard', promotions: 'Acties', trade: 'Handel',
    streaming: 'Streaming', leaderboard: 'Ranglijst', activity: 'Activiteit', parlays: 'Combi',
    withdraw: 'Opnemen', whitepaper: 'Whitepaper', searchTeams: 'Zoek teams, competities...',
    favorites: 'Favorieten', withOdds: 'Met Odds', live: 'Live', upcoming: 'Aankomend',
    loading: 'Evenementen laden...', noEvents: 'Geen evenementen beschikbaar',
    bettingClosed: 'Wedden gesloten', betSlip: 'Wedformulier', parlay: 'Combi',
    tapOdds: 'Tik op odds om selecties toe te voegen', stake: 'Inzet', potentialWin: 'Mogelijke Winst',
    placeBet: 'Weddenschap plaatsen', connectWallet: 'Wallet verbinden', disconnect: 'Verbreken',
    balance: 'Saldo', deposit: 'Storten', totalBets: 'Totaal Weddenschappen', activeBets: 'Actieve Weddenschappen',
    volume: 'Volume', matches: 'wedstrijden', match: 'wedstrijd', home: 'Thuis', draw: 'Gelijk', away: 'Uit',
    over: 'Meer dan', under: 'Minder dan', cashOut: 'Uitbetalen', cashOutConfirm: 'Uitbetaling bevestigen',
    notifications: 'Meldingen', noNotifications: 'Geen nieuwe meldingen',
    betWon: 'Weddenschap gewonnen!', betLost: 'Weddenschap verloren', betSettled: 'Weddenschap afgerond',
    clearAll: 'Alles wissen', verifiedOnSui: 'Geverifieerd op Sui', poweredBy: 'Aangedreven door',
    language: 'Taal', starTeams: 'Voeg teams toe aan favorieten!',
    formulaNote: 'F1 races worden wekelijks bijgewerkt', mmaNote: 'MMA evenementen worden periodiek bijgewerkt',
    clear: 'Wissen', viewAll: 'Alles bekijken',
    heroTitle: 'Gedecentraliseerd Sportwedden op', heroSui: 'Sui',
      heroSubtitle: 'Wed met SBETS of SUI \u00b7 Transparante odds \u00b7 Directe on-chain afwikkeling',
      liveMarkets: 'Live Markten', sports: 'Sporten', settlement: 'Afwikkeling', onChain: 'On-Chain',
      betsSettled: 'Afgewikkelde Weddenschappen', sbetsVolume: 'SBETS Volume', viewContract: 'Contract Bekijken',
      more: 'Meer', buyNow: 'Kopen', checkBackLater: 'Kom later terug voor meer evenementen',
      noEventsTab: 'Geen {tab} evenementen beschikbaar',
  },
  pl: {
    bets: 'Zakłady', predict: 'Przewidywanie', aiBetting: 'AI Zakłady', myBets: 'Moje Zakłady',
    revenue: 'Przychody', dashboard: 'Panel', promotions: 'Promocje', trade: 'Handel',
    streaming: 'Streaming', leaderboard: 'Ranking', activity: 'Aktywność', parlays: 'Akumulatory',
    withdraw: 'Wypłata', whitepaper: 'Whitepaper', searchTeams: 'Szukaj drużyn, lig...',
    favorites: 'Ulubione', withOdds: 'Z kursami', live: 'Na żywo', upcoming: 'Nadchodzące',
    loading: 'Ładowanie wydarzeń...', noEvents: 'Brak dostępnych wydarzeń',
    bettingClosed: 'Zakłady zamknięte', betSlip: 'Kupon', parlay: 'Akumulator',
    tapOdds: 'Dotknij kursów aby dodać wybory', stake: 'Stawka', potentialWin: 'Potencjalna Wygrana',
    placeBet: 'Postaw zakład', connectWallet: 'Podłącz portfel', disconnect: 'Odłącz',
    balance: 'Saldo', deposit: 'Wpłata', totalBets: 'Suma Zakładów', activeBets: 'Aktywne Zakłady',
    volume: 'Obrót', matches: 'mecze', match: 'mecz', home: 'Gospodarz', draw: 'Remis', away: 'Gość',
    over: 'Powyżej', under: 'Poniżej', cashOut: 'Wypłać', cashOutConfirm: 'Potwierdź wypłatę',
    notifications: 'Powiadomienia', noNotifications: 'Brak nowych powiadomień',
    betWon: 'Zakład wygrany!', betLost: 'Zakład przegrany', betSettled: 'Zakład rozliczony',
    clearAll: 'Wyczyść wszystko', verifiedOnSui: 'Zweryfikowane na Sui', poweredBy: 'Obsługiwane przez',
    language: 'Język', starTeams: 'Dodaj drużyny do ulubionych!',
    formulaNote: 'Wyścigi F1 aktualizowane co tydzień', mmaNote: 'Wydarzenia MMA aktualizowane okresowo',
    clear: 'Wyczyść', viewAll: 'Zobacz wszystko',
    heroTitle: 'Zdecentralizowane Zakłady Sportowe na', heroSui: 'Sui',
      heroSubtitle: 'Obstawiaj SBETS lub SUI \u00b7 Przejrzyste kursy \u00b7 Natychmiastowe rozliczenie on-chain',
      liveMarkets: 'Rynki na Żywo', sports: 'Sporty', settlement: 'Rozliczenie', onChain: 'On-Chain',
      betsSettled: 'Rozliczone Zakłady', sbetsVolume: 'Wolumen SBETS', viewContract: 'Zobacz Kontrakt',
      more: 'Więcej', buyNow: 'Kup', checkBackLater: 'Wróć później po więcej wydarzeń',
      noEventsTab: 'Brak wydarzeń {tab}',
  },
  sv: {
    bets: 'Spel', predict: 'Förutsäga', aiBetting: 'AI-spel', myBets: 'Mina Spel',
    revenue: 'Intäkter', dashboard: 'Översikt', promotions: 'Kampanjer', trade: 'Handel',
    streaming: 'Streaming', leaderboard: 'Topplista', activity: 'Aktivitet', parlays: 'Kombispel',
    withdraw: 'Uttag', whitepaper: 'Whitepaper', searchTeams: 'Sök lag, ligor...',
    favorites: 'Favoriter', withOdds: 'Med odds', live: 'Live', upcoming: 'Kommande',
    loading: 'Laddar evenemang...', noEvents: 'Inga evenemang tillgängliga',
    bettingClosed: 'Spel stängt', betSlip: 'Spelsedel', parlay: 'Kombination',
    tapOdds: 'Tryck på odds för att lägga till val', stake: 'Insats', potentialWin: 'Möjlig Vinst',
    placeBet: 'Lägg spel', connectWallet: 'Anslut plånbok', disconnect: 'Koppla från',
    balance: 'Saldo', deposit: 'Insättning', totalBets: 'Totalt Spel', activeBets: 'Aktiva Spel',
    volume: 'Volym', matches: 'matcher', match: 'match', home: 'Hemma', draw: 'Oavgjort', away: 'Borta',
    over: 'Över', under: 'Under', cashOut: 'Ta ut', cashOutConfirm: 'Bekräfta uttag',
    notifications: 'Aviseringar', noNotifications: 'Inga nya aviseringar',
    betWon: 'Spel vunnet!', betLost: 'Spel förlorat', betSettled: 'Spel avgjort',
    clearAll: 'Rensa allt', verifiedOnSui: 'Verifierat på Sui', poweredBy: 'Drivs av',
    language: 'Språk', starTeams: 'Lägg till lag som favoriter!',
    formulaNote: 'F1-lopp uppdateras veckovis', mmaNote: 'MMA-evenemang uppdateras periodiskt',
    clear: 'Rensa', viewAll: 'Visa alla',
    heroTitle: 'Decentraliserat Sportspel på', heroSui: 'Sui',
      heroSubtitle: 'Satsa med SBETS eller SUI \u00b7 Transparenta odds \u00b7 Omedelbar on-chain-avräkning',
      liveMarkets: 'Live-marknader', sports: 'Sporter', settlement: 'Avräkning', onChain: 'On-Chain',
      betsSettled: 'Avgjorda Spel', sbetsVolume: 'SBETS Volym', viewContract: 'Visa Kontrakt',
      more: 'Mer', buyNow: 'Köp', checkBackLater: 'Kom tillbaka senare för fler evenemang',
      noEventsTab: 'Inga {tab} evenemang tillgängliga',
  },
  th: {
    bets: 'เดิมพัน', predict: 'ทำนาย', aiBetting: 'AI เดิมพัน', myBets: 'เดิมพันของฉัน',
    revenue: 'รายได้', dashboard: 'แดชบอร์ด', promotions: 'โปรโมชั่น', trade: 'ซื้อขาย',
    streaming: 'สตรีมมิ่ง', leaderboard: 'อันดับ', activity: 'กิจกรรม', parlays: 'พาร์เลย์',
    withdraw: 'ถอน', whitepaper: 'เอกสาร', searchTeams: 'ค้นหาทีม, ลีก...',
    favorites: 'รายการโปรด', withOdds: 'มีอัตรา', live: 'สด', upcoming: 'ใกล้เริ่ม',
    loading: 'กำลังโหลด...', noEvents: 'ไม่มีกิจกรรม',
    bettingClosed: 'ปิดรับเดิมพัน', betSlip: 'ใบเดิมพัน', parlay: 'พาร์เลย์',
    tapOdds: 'แตะอัตราเพื่อเพิ่มตัวเลือก', stake: 'เงินเดิมพัน', potentialWin: 'ผลตอบแทน',
    placeBet: 'วางเดิมพัน', connectWallet: 'เชื่อมต่อกระเป๋า', disconnect: 'ตัดการเชื่อมต่อ',
    balance: 'ยอดคงเหลือ', deposit: 'ฝาก', totalBets: 'เดิมพันทั้งหมด', activeBets: 'เดิมพันที่ใช้งาน',
    volume: 'ปริมาณ', matches: 'แมตช์', match: 'แมตช์', home: 'เจ้าบ้าน', draw: 'เสมอ', away: 'ทีมเยือน',
    over: 'สูง', under: 'ต่ำ', cashOut: 'ถอนเงิน', cashOutConfirm: 'ยืนยันการถอน',
    notifications: 'การแจ้งเตือน', noNotifications: 'ไม่มีการแจ้งเตือนใหม่',
    betWon: 'เดิมพันชนะ!', betLost: 'เดิมพันแพ้', betSettled: 'เดิมพันตัดสิน',
    clearAll: 'ล้างทั้งหมด', verifiedOnSui: 'ยืนยันบน Sui', poweredBy: 'ขับเคลื่อนโดย',
    language: 'ภาษา', starTeams: 'เพิ่มทีมในรายการโปรด!',
    formulaNote: 'อัพเดท F1 ทุกสัปดาห์', mmaNote: 'อัพเดท MMA เป็นระยะ',
    clear: 'ล้าง', viewAll: 'ดูทั้งหมด',
    heroTitle: 'การเดิมพันกีฬาแบบกระจายศูนย์บน', heroSui: 'Sui',
      heroSubtitle: 'เดิมพันด้วย SBETS หรือ SUI \u00b7 อัตราต่อรองโปร่งใส \u00b7 การชำระเงินทันทีบนเชน',
      liveMarkets: 'ตลาดสด', sports: 'กีฬา', settlement: 'การชำระ', onChain: 'บนเชน',
      betsSettled: 'การเดิมพันที่ชำระแล้ว', sbetsVolume: 'ปริมาณ SBETS', viewContract: 'ดูสัญญา',
      more: 'เพิ่มเติม', buyNow: 'ซื้อ', checkBackLater: 'กลับมาภายหลังเพื่อดูเหตุการณ์เพิ่มเติม',
      noEventsTab: 'ไม่มีเหตุการณ์{tab}',
  },
  vi: {
    bets: 'Cược', predict: 'Dự đoán', aiBetting: 'AI Cá Cược', myBets: 'Cược Của Tôi',
    revenue: 'Doanh thu', dashboard: 'Bảng điều khiển', promotions: 'Khuyến mãi', trade: 'Giao dịch',
    streaming: 'Phát sóng', leaderboard: 'Bảng xếp hạng', activity: 'Hoạt động', parlays: 'Kèo chấp',
    withdraw: 'Rút tiền', whitepaper: 'Whitepaper', searchTeams: 'Tìm đội, giải đấu...',
    favorites: 'Yêu thích', withOdds: 'Có tỷ lệ', live: 'Trực tiếp', upcoming: 'Sắp tới',
    loading: 'Đang tải sự kiện...', noEvents: 'Không có sự kiện',
    bettingClosed: 'Đã đóng cược', betSlip: 'Phiếu cược', parlay: 'Kèo combo',
    tapOdds: 'Chạm vào tỷ lệ để thêm lựa chọn', stake: 'Tiền cược', potentialWin: 'Lợi nhuận',
    placeBet: 'Đặt cược', connectWallet: 'Kết nối ví', disconnect: 'Ngắt kết nối',
    balance: 'Số dư', deposit: 'Nạp tiền', totalBets: 'Tổng cược', activeBets: 'Cược đang chạy',
    volume: 'Khối lượng', matches: 'trận', match: 'trận', home: 'Chủ nhà', draw: 'Hòa', away: 'Khách',
    over: 'Trên', under: 'Dưới', cashOut: 'Rút sớm', cashOutConfirm: 'Xác nhận rút',
    notifications: 'Thông báo', noNotifications: 'Không có thông báo mới',
    betWon: 'Cược thắng!', betLost: 'Cược thua', betSettled: 'Cược đã xử lý',
    clearAll: 'Xóa tất cả', verifiedOnSui: 'Xác minh trên Sui', poweredBy: 'Hỗ trợ bởi',
    language: 'Ngôn ngữ', starTeams: 'Thêm đội yêu thích để xem tại đây!',
    formulaNote: 'Đua F1 cập nhật hàng tuần', mmaNote: 'Sự kiện MMA cập nhật định kỳ',
    clear: 'Xóa', viewAll: 'Xem tất cả',
    heroTitle: 'Cá Cược Thể Thao Phi Tập Trung trên', heroSui: 'Sui',
      heroSubtitle: 'Đặt cược bằng SBETS hoặc SUI \u00b7 Tỷ lệ cược minh bạch \u00b7 Thanh toán tức thì on-chain',
      liveMarkets: 'Thị Trường Trực Tiếp', sports: 'Thể Thao', settlement: 'Thanh Toán', onChain: 'On-Chain',
      betsSettled: 'Cược Đã Thanh Toán', sbetsVolume: 'Khối Lượng SBETS', viewContract: 'Xem Hợp Đồng',
      more: 'Thêm', buyNow: 'Mua', checkBackLater: 'Quay lại sau để xem thêm sự kiện',
      noEventsTab: 'Không có sự kiện {tab} nào',
  },
  id: {
    bets: 'Taruhan', predict: 'Prediksi', aiBetting: 'AI Taruhan', myBets: 'Taruhan Saya',
    revenue: 'Pendapatan', dashboard: 'Dasbor', promotions: 'Promosi', trade: 'Perdagangan',
    streaming: 'Streaming', leaderboard: 'Papan Peringkat', activity: 'Aktivitas', parlays: 'Parlay',
    withdraw: 'Tarik', whitepaper: 'Whitepaper', searchTeams: 'Cari tim, liga...',
    favorites: 'Favorit', withOdds: 'Dengan Odds', live: 'Langsung', upcoming: 'Mendatang',
    loading: 'Memuat acara...', noEvents: 'Tidak ada acara tersedia',
    bettingClosed: 'Taruhan ditutup', betSlip: 'Slip Taruhan', parlay: 'Parlay',
    tapOdds: 'Ketuk odds untuk menambah pilihan', stake: 'Taruhan', potentialWin: 'Potensi Menang',
    placeBet: 'Pasang Taruhan', connectWallet: 'Hubungkan Dompet', disconnect: 'Putuskan',
    balance: 'Saldo', deposit: 'Setor', totalBets: 'Total Taruhan', activeBets: 'Taruhan Aktif',
    volume: 'Volume', matches: 'pertandingan', match: 'pertandingan', home: 'Tuan Rumah', draw: 'Seri', away: 'Tamu',
    over: 'Atas', under: 'Bawah', cashOut: 'Cairkan', cashOutConfirm: 'Konfirmasi Pencairan',
    notifications: 'Notifikasi', noNotifications: 'Tidak ada notifikasi baru',
    betWon: 'Taruhan Menang!', betLost: 'Taruhan Kalah', betSettled: 'Taruhan Selesai',
    clearAll: 'Hapus Semua', verifiedOnSui: 'Terverifikasi di Sui', poweredBy: 'Didukung oleh',
    language: 'Bahasa', starTeams: 'Tambahkan tim ke favorit untuk melihatnya di sini!',
    formulaNote: 'Balapan F1 diperbarui setiap minggu', mmaNote: 'Acara MMA diperbarui secara berkala',
    clear: 'Hapus', viewAll: 'Lihat Semua',
    heroTitle: 'Taruhan Olahraga Terdesentralisasi di', heroSui: 'Sui',
      heroSubtitle: 'Taruhan dengan SBETS atau SUI \u00b7 Odds transparan \u00b7 Penyelesaian instan on-chain',
      liveMarkets: 'Pasar Live', sports: 'Olahraga', settlement: 'Penyelesaian', onChain: 'On-Chain',
      betsSettled: 'Taruhan Diselesaikan', sbetsVolume: 'Volume SBETS', viewContract: 'Lihat Kontrak',
      more: 'Lainnya', buyNow: 'Beli', checkBackLater: 'Kembali lagi nanti untuk lebih banyak acara',
      noEventsTab: 'Tidak ada acara {tab} tersedia',
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: TranslationKey) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  language: 'en',
  setLanguage: () => {},
  t: (key) => key,
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('suibets-language');
    return (saved as Language) || 'en';
  });

  const setLanguage = useCallback((lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('suibets-language', lang);
  }, []);

  const t = useCallback((key: TranslationKey): string => {
    return translations[language]?.[key] || translations.en[key] || key;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
