[package]
name = "warp_engine"
edition = "2024.beta"
published-at = "0x9c36e734411dbb124b5b7e0f0f34dcf424e05131877d5523a101f8d7b6d39747"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "mainnet-v1.68.1", override = true }
p2p_betting = { local = "../p2p_betting" }

[addresses]
warp_engine = "0x0"
p2p_betting = "0xd51fe151bec66a15b086a67c1cfce9b05759ddac1d73fcd3e14324ad202b2e59"
